### ISSUE TITLE
children of component children do not scroll

### ISSUE THREAD

**Issue by KevinHerklotz** [theKashey/react-remove-scroll#14]
Thanks for this library! Unfortunately I have some unwanted behaviour:
Scrolling inside nested divs does not work anymore with the mouse wheel. Only manually when I touch the scrollbar on the right.

**Comment by theKashey** [comment]
As long as I could not control and prevent manual scrollbar dragging. However nested divs should work fine, probably there is something tricky with your markup and I could not properly measure available scroll size.
I don't need a real example to reproduce the issue - only a piece of HTML and CSS.

All logic is here - https://github.com/theKashey/react-remove-scroll/blob/master/src/handleScroll.ts

First it checks if scroll is possible in the "main direction":
https://github.com/theKashey/react-remove-scroll/blob/3a0f69e8a824681277b77f176c57e5917e6c5a16/src/SideEffect.tsx#L76-L80
and early exists if not

Later checks that you have enought scroll space 
https://github.com/theKashey/react-remove-scroll/blob/3a0f69e8a824681277b77f176c57e5917e6c5a16/src/handleScroll.ts#L77-L81

Just place breakpoint to these location to determine which one prevent scrolling, and then you will be able to reason about root cause.

**Comment by KevinHerklotz** [comment]
I think the problem is that my modal has `position: fixed`. (I use the default Dialog from MUI)
I cannot get it to work 😞 
But thanks for your help anyways!

**Comment by theKashey** [comment]
No, position fixed is ok, but `MUI` might be not. `MUI` has own integrated `focus` and `scroll lock`, and they might be killing each other.
Are you sure you need `focus-on` with `MUI`?

**Comment by KevinHerklotz** [comment]
Hey I found out the issue 🎉 
The problem was that for some reasons the nested `div`s had the style `overflow-y: auto;`.
I changed that to `overflow-y: scroll;` and now everything works!
Maybe you can add this to your documentation.
Thanks again for your help!

**Comment by theKashey** [comment]
Checking other examples - and it works with `auto` as well as with `scroll`. Are you sure it was the only change?
