### ISSUE TITLE
Short interval touch events are not recognized in Safari

### ISSUE THREAD

**Issue by mottox2** [theKashey/react-remove-scroll#26]
Before react-remove-scroll mounted, it can detect taps at short interval (e.g. double tap), but once mounted it sometimes fails to recognize the double tap.

## Reproduction
[reproduction in codesandbox](https://codesandbox.io/s/remove-scroll-n42we)

1. Open [this URL](https://codesandbox.io/s/remove-scroll-n42we) in iOS Safari (iOS 13.4+).
2. Make sure it counts up 2 with a double tap.
3. Tap "Toggle RemoveScroll" button. (it makes react-remove-scroll mounted.)
4. Double-tap to check that sometimes only one counts up.

I've seen this happen on iOS 13.4 and 13.5. but **not** on iOS 13.3 and iOS 12.2.

**Comment by theKashey** [comment]
That's very interesting observation - look like something is preventing events from happening "faster" than 300ms each(I've measured), which is basically "onClick".

In other words that might mean that remove scroll by some way disabled `touch end` at all.
Probably the root cause is somewhere inside react and using `onTouchMoveCapture` triggers that behavior.
https://github.com/theKashey/react-remove-scroll/blob/master/src/UI.tsx#L30
