### ISSUE TITLE
Maybe a simpler solution

### ISSUE THREAD

**Issue by doliG** [theKashey/react-remove-scroll#80]
Disabling scroll in CSS is as simple as 

```css
.parent { overflow: hidden }
.children { overflow: scroll }
```

And can probably be implemented like this
```js
const setOverflowOnBody = (value = '') => {
  document.querySelector('body').style.overflow = value
}

const DisableScroll = (props) => {
  useEffect(() => {
    setOverflowOnBody('hidden')
    return () => setOverflowOnBody('')
  }, []);

  return <>{props.children}</>
}
```

So I'm not sure to understand the purpose of this library, which replace few lines of CSS by 2.5kB of JS 🤔 

The goal of my message is not to sound rude, I'm simply trying to understand what are the benefits of using this lib. Thanks for your help 🙏

**Comment by theKashey** [comment]
The functionality you talk about is more about https://github.com/theKashey/react-remove-scroll-bar
In fact it is a little more complicated because we don't want to introduce a "layout shift" when your page may become `scroll-bar-width` wider. And still want some elements (like header) to stretch from end to end.

This particular library, build on top of `remove-scroll-bar` was initially created to handle iOS, which does not disable scroll when you add `overflow:hidden` on body. Today, it can handle scroll prevention for any use case possible. Not only "page-wide", but local.

Once I had example of allowing scroll in a sidebar, but not allowing it to scroll the rest of the page once you reach the end.
